import os
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("BOT_TOKEN", "8973072159:AAHHqRXaDePf6qmB3muzfKypKh4JBOHWCFo")

START_MONEY = 500
FOOD_COST_PER_ANIMAL = 15
SELL_ANIMAL_PRICE = 50

CROP_DATA = {
    "🌾Пшеница": {"cost": 50, "min_yield": 5, "max_yield": 15, "emoji": "🌾", "unlock_requirement": 0, "unlock_crop": None},
    "🌽Кукуруза": {"cost": 80, "min_yield": 5, "max_yield": 15, "emoji": "🌽", "unlock_requirement": 10, "unlock_crop": "🌾Пшеница"},
    "🥔Картофель": {"cost": 60, "min_yield": 8, "max_yield": 20, "emoji": "🥔", "unlock_requirement": 15, "unlock_crop": "🌽Кукуруза"},
    "🥕Морковь": {"cost": 70, "min_yield": 6, "max_yield": 18, "emoji": "🥕", "unlock_requirement": 20, "unlock_crop": "🥔Картофель"},
    "🧅Лук": {"cost": 40, "min_yield": 10, "max_yield": 25, "emoji": "🧅", "unlock_requirement": 25, "unlock_crop": "🥕Морковь"},
    "🌶️Перец": {"cost": 90, "min_yield": 5, "max_yield": 12, "emoji": "🌶️", "unlock_requirement": 30, "unlock_crop": "🧅Лук"},
    "🍅Помидоры": {"cost": 120, "min_yield": 5, "max_yield": 15, "emoji": "🍅", "unlock_requirement": 35, "unlock_crop": "🌶️Перец"},
    "🍆Баклажан": {"cost": 100, "min_yield": 4, "max_yield": 10, "emoji": "🍆", "unlock_requirement": 40, "unlock_crop": "🍅Помидоры"},
    "🥦Брокколи": {"cost": 110, "min_yield": 5, "max_yield": 12, "emoji": "🥦", "unlock_requirement": 45, "unlock_crop": "🍆Баклажан"},
    "🌿Салат": {"cost": 30, "min_yield": 10, "max_yield": 30, "emoji": "🌿", "unlock_requirement": 50, "unlock_crop": "🥦Брокколи"},
    "🍓Клубника": {"cost": 150, "min_yield": 4, "max_yield": 10, "emoji": "🍓", "unlock_requirement": 20, "unlock_crop": "🌿Салат"},
    "🍋Лимон": {"cost": 130, "min_yield": 4, "max_yield": 10, "emoji": "🍋", "unlock_requirement": 25, "unlock_crop": "🍓Клубника"},
    "🍑Персик": {"cost": 160, "min_yield": 3, "max_yield": 7, "emoji": "🍑", "unlock_requirement": 30, "unlock_crop": "🍋Лимон"},
    "🍇Виноград": {"cost": 180, "min_yield": 3, "max_yield": 8, "emoji": "🍇", "unlock_requirement": 35, "unlock_crop": "🍑Персик"},
    "🍉Арбуз": {"cost": 200, "min_yield": 2, "max_yield": 5, "emoji": "🍉", "unlock_requirement": 40, "unlock_crop": "🍇Виноград"},
    "🥭Манго": {"cost": 220, "min_yield": 2, "max_yield": 5, "emoji": "🥭", "unlock_requirement": 45, "unlock_crop": "🍉Арбуз"},
    "🍍Ананас": {"cost": 250, "min_yield": 2, "max_yield": 4, "emoji": "🍍", "unlock_requirement": 50, "unlock_crop": "🥭Манго"},
    "🥑Авокадо": {"cost": 300, "min_yield": 2, "max_yield": 4, "emoji": "🥑", "unlock_requirement": 30, "unlock_crop": "🍍Ананас"},
    "🍌Банан": {"cost": 140, "min_yield": 4, "max_yield": 8, "emoji": "🍌", "unlock_requirement": 20, "unlock_crop": "🥑Авокадо"},
    "🍎Яблоко": {"cost": 100, "min_yield": 5, "max_yield": 12, "emoji": "🍎", "unlock_requirement": 15, "unlock_crop": "🍌Банан"},
    "🍐Груша": {"cost": 120, "min_yield": 4, "max_yield": 10, "emoji": "🍐", "unlock_requirement": 20, "unlock_crop": "🍎Яблоко"},
    "🍒Вишня": {"cost": 150, "min_yield": 4, "max_yield": 8, "emoji": "🍒", "unlock_requirement": 25, "unlock_crop": "🍐Груша"},
    "🍊Апельсин": {"cost": 130, "min_yield": 4, "max_yield": 10, "emoji": "🍊", "unlock_requirement": 30, "unlock_crop": "🍒Вишня"},
    "🍈Дыня": {"cost": 190, "min_yield": 2, "max_yield": 5, "emoji": "🍈", "unlock_requirement": 35, "unlock_crop": "🍊Апельсин"},
    "🥝Киви": {"cost": 160, "min_yield": 3, "max_yield": 7, "emoji": "🥝", "unlock_requirement": 40, "unlock_crop": "🍈Дыня"},
    "🍄Грибы": {"cost": 80, "min_yield": 6, "max_yield": 15, "emoji": "🍄", "unlock_requirement": 15, "unlock_crop": "🥝Киви"},
    "🌻Подсолнух": {"cost": 50, "min_yield": 8, "max_yield": 20, "emoji": "🌻", "unlock_requirement": 20, "unlock_crop": "🍄Грибы"},
    "🌹Роза": {"cost": 200, "min_yield": 3, "max_yield": 7, "emoji": "🌹", "unlock_requirement": 25, "unlock_crop": "🌻Подсолнух"},
    "🌺Тюльпан": {"cost": 150, "min_yield": 4, "max_yield": 8, "emoji": "🌺", "unlock_requirement": 30, "unlock_crop": "🌹Роза"},
    "🌸Сакура": {"cost": 300, "min_yield": 2, "max_yield": 4, "emoji": "🌸", "unlock_requirement": 35, "unlock_crop": "🌺Тюльпан"},
    "🌿Мята": {"cost": 40, "min_yield": 12, "max_yield": 30, "emoji": "🌿", "unlock_requirement": 40, "unlock_crop": "🌸Сакура"},
    "🌱Бамбук": {"cost": 70, "min_yield": 8, "max_yield": 20, "emoji": "🌱", "unlock_requirement": 20, "unlock_crop": "🌿Мята"},
    "🍀Клевер": {"cost": 30, "min_yield": 15, "max_yield": 35, "emoji": "🍀", "unlock_requirement": 25, "unlock_crop": "🌱Бамбук"},
    "🌾Рис": {"cost": 40, "min_yield": 10, "max_yield": 25, "emoji": "🌾", "unlock_requirement": 30, "unlock_crop": "🍀Клевер"},
    "🫘Соя": {"cost": 60, "min_yield": 8, "max_yield": 20, "emoji": "🫘", "unlock_requirement": 35, "unlock_crop": "🌾Рис"},
    "🫛Горох": {"cost": 50, "min_yield": 10, "max_yield": 25, "emoji": "🫛", "unlock_requirement": 40, "unlock_crop": "🫘Соя"},
    "🥜Арахис": {"cost": 70, "min_yield": 6, "max_yield": 15, "emoji": "🥜", "unlock_requirement": 45, "unlock_crop": "🫛Горох"},
    "🌰Каштан": {"cost": 180, "min_yield": 3, "max_yield": 7, "emoji": "🌰", "unlock_requirement": 50, "unlock_crop": "🥜Арахис"},
    "🌽Сладкая кукуруза": {"cost": 100, "min_yield": 5, "max_yield": 12, "emoji": "🌽", "unlock_requirement": 20, "unlock_crop": "🌰Каштан"},
    "🍠Батат": {"cost": 80, "min_yield": 6, "max_yield": 15, "emoji": "🍠", "unlock_requirement": 25, "unlock_crop": "🌽Сладкая кукуруза"},
    "🥬Капуста": {"cost": 50, "min_yield": 10, "max_yield": 25, "emoji": "🥬", "unlock_requirement": 30, "unlock_crop": "🍠Батат"},
    "🥒Огурец": {"cost": 70, "min_yield": 6, "max_yield": 15, "emoji": "🥒", "unlock_requirement": 35, "unlock_crop": "🥬Капуста"},
    "🫑Болгарский перец": {"cost": 90, "min_yield": 5, "max_yield": 12, "emoji": "🫑", "unlock_requirement": 40, "unlock_crop": "🥒Огурец"},
    "🧄Чеснок": {"cost": 60, "min_yield": 8, "max_yield": 20, "emoji": "🧄", "unlock_requirement": 45, "unlock_crop": "🫑Болгарский перец"},
    "🫚Имбирь": {"cost": 100, "min_yield": 5, "max_yield": 12, "emoji": "🫚", "unlock_requirement": 50, "unlock_crop": "🧄Чеснок"},
    "🌶️Чили": {"cost": 80, "min_yield": 6, "max_yield": 15, "emoji": "🌶️", "unlock_requirement": 20, "unlock_crop": "🫚Имбирь"},
    "🥝Зелёный киви": {"cost": 140, "min_yield": 4, "max_yield": 8, "emoji": "🥝", "unlock_requirement": 25, "unlock_crop": "🌶️Чили"},
    "🫐Голубика": {"cost": 180, "min_yield": 4, "max_yield": 8, "emoji": "🫐", "unlock_requirement": 30, "unlock_crop": "🥝Зелёный киви"},
    "🍒Черешня": {"cost": 160, "min_yield": 3, "max_yield": 7, "emoji": "🍒", "unlock_requirement": 35, "unlock_crop": "🫐Голубика"},
    "🥬Пекинская капуста": {"cost": 45, "min_yield": 10, "max_yield": 25, "emoji": "🥬", "unlock_requirement": 40, "unlock_crop": "🍒Черешня"}
}

ANIMAL_DATA = {
    "🐔Куры": {"cost": 200, "product": "🥚", "min_prod": 1, "max_prod": 3, "price_per_unit": 10, "emoji": "🐔"},
    "🐄Коровы": {"cost": 500, "product": "🥛", "min_prod": 2, "max_prod": 5, "price_per_unit": 20, "emoji": "🐄"},
    "🐑Овцы": {"cost": 400, "product": "🧶", "min_prod": 1, "max_prod": 2, "price_per_unit": 30, "emoji": "🐑"},
    "🐖Свиньи": {"cost": 300, "product": "🥩", "min_prod": 1, "max_prod": 2, "price_per_unit": 50, "emoji": "🐖"},
    "🐐Козы": {"cost": 350, "product": "🥛", "min_prod": 2, "max_prod": 4, "price_per_unit": 25, "emoji": "🐐"},
    "🦆Утки": {"cost": 150, "product": "🥚", "min_prod": 2, "max_prod": 4, "price_per_unit": 8, "emoji": "🦆"},
    "🐇Кролики": {"cost": 100, "product": "🧶", "min_prod": 1, "max_prod": 3, "price_per_unit": 15, "emoji": "🐇"},
    "🐝Пчёлы": {"cost": 250, "product": "🍯", "min_prod": 3, "max_prod": 6, "price_per_unit": 35, "emoji": "🐝"},
    "🦃Индейки": {"cost": 450, "product": "🥚", "min_prod": 1, "max_prod": 2, "price_per_unit": 40, "emoji": "🦃"},
    "🐴Лошади": {"cost": 600, "product": "💨", "min_prod": 1, "max_prod": 2, "price_per_unit": 60, "emoji": "🐴"},
    "🐫Верблюды": {"cost": 700, "product": "🥛", "min_prod": 1, "max_prod": 3, "price_per_unit": 45, "emoji": "🐫"},
    "🦙Ламы": {"cost": 550, "product": "🧶", "min_prod": 1, "max_prod": 3, "price_per_unit": 35, "emoji": "🦙"},
    "🐂Быки": {"cost": 800, "product": "🥩", "min_prod": 1, "max_prod": 2, "price_per_unit": 70, "emoji": "🐂"},
    "🐃Буйволы": {"cost": 900, "product": "🥛", "min_prod": 1, "max_prod": 3, "price_per_unit": 50, "emoji": "🐃"},
    "🦌Олени": {"cost": 650, "product": "🧶", "min_prod": 1, "max_prod": 2, "price_per_unit": 55, "emoji": "🦌"},
    "🐕Собаки": {"cost": 250, "product": "🛡️", "min_prod": 1, "max_prod": 2, "price_per_unit": 20, "emoji": "🐕"},
    "🐈Коты": {"cost": 200, "product": "🐁", "min_prod": 1, "max_prod": 3, "price_per_unit": 15, "emoji": "🐈"},
    "🐓Петухи": {"cost": 180, "product": "🥚", "min_prod": 1, "max_prod": 2, "price_per_unit": 12, "emoji": "🐓"},
    "🦅Орлы": {"cost": 1000, "product": "🪶", "min_prod": 1, "max_prod": 2, "price_per_unit": 80, "emoji": "🦅"},
    "🦉Совы": {"cost": 800, "product": "🪶", "min_prod": 1, "max_prod": 2, "price_per_unit": 60, "emoji": "🦉"},
    "🐧Пингвины": {"cost": 600, "product": "🥚", "min_prod": 1, "max_prod": 2, "price_per_unit": 40, "emoji": "🐧"},
    "🦢Лебеди": {"cost": 700, "product": "🪶", "min_prod": 1, "max_prod": 2, "price_per_unit": 50, "emoji": "🦢"},
    "🦜Попугаи": {"cost": 500, "product": "🪶", "min_prod": 1, "max_prod": 3, "price_per_unit": 30, "emoji": "🦜"},
    "🐦Воробьи": {"cost": 100, "product": "🪶", "min_prod": 2, "max_prod": 5, "price_per_unit": 8, "emoji": "🐦"},
    "🦇Летучие мыши": {"cost": 300, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 25, "emoji": "🦇"},
    "🐊Крокодилы": {"cost": 1200, "product": "🧪", "min_prod": 1, "max_prod": 2, "price_per_unit": 100, "emoji": "🐊"},
    "🦎Ящерицы": {"cost": 400, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 30, "emoji": "🦎"},
    "🐢Черепахи": {"cost": 500, "product": "🥚", "min_prod": 1, "max_prod": 2, "price_per_unit": 35, "emoji": "🐢"},
    "🐍Змеи": {"cost": 450, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 30, "emoji": "🐍"},
    "🦞Лобстеры": {"cost": 600, "product": "🧪", "min_prod": 1, "max_prod": 2, "price_per_unit": 45, "emoji": "🦞"},
    "🦀Крабы": {"cost": 400, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 25, "emoji": "🦀"},
    "🐚Улитки": {"cost": 100, "product": "🧪", "min_prod": 2, "max_prod": 5, "price_per_unit": 10, "emoji": "🐚"},
    "🦋Бабочки": {"cost": 300, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 20, "emoji": "🦋"},
    "🐞Божьи коровки": {"cost": 150, "product": "🧪", "min_prod": 2, "max_prod": 4, "price_per_unit": 15, "emoji": "🐞"},
    "🦗Сверчки": {"cost": 100, "product": "🧪", "min_prod": 2, "max_prod": 5, "price_per_unit": 10, "emoji": "🦗"},
    "🪲Жуки": {"cost": 200, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 15, "emoji": "🪲"},
    "🐜Муравьи": {"cost": 80, "product": "🧪", "min_prod": 3, "max_prod": 6, "price_per_unit": 8, "emoji": "🐜"},
    "🪰Мухи": {"cost": 50, "product": "🧪", "min_prod": 3, "max_prod": 8, "price_per_unit": 5, "emoji": "🪰"},
    "🪟Мотыльки": {"cost": 120, "product": "🧪", "min_prod": 2, "max_prod": 4, "price_per_unit": 12, "emoji": "🪟"},
    "🐛Гусеницы": {"cost": 80, "product": "🧪", "min_prod": 2, "max_prod": 5, "price_per_unit": 8, "emoji": "🐛"},
    "🪱Черви": {"cost": 60, "product": "🧪", "min_prod": 3, "max_prod": 7, "price_per_unit": 6, "emoji": "🪱"},
    "🐌Слизни": {"cost": 70, "product": "🧪", "min_prod": 2, "max_prod": 5, "price_per_unit": 7, "emoji": "🐌"},
    "🪳Тараканы": {"cost": 80, "product": "🧪", "min_prod": 2, "max_prod": 6, "price_per_unit": 8, "emoji": "🪳"},
    "🦟Комары": {"cost": 70, "product": "🧪", "min_prod": 3, "max_prod": 7, "price_per_unit": 7, "emoji": "🦟"},
    "🪰Осы": {"cost": 120, "product": "🧪", "min_prod": 2, "max_prod": 4, "price_per_unit": 12, "emoji": "🪰"},
    "🦂Скорпионы": {"cost": 500, "product": "🧪", "min_prod": 1, "max_prod": 2, "price_per_unit": 40, "emoji": "🦂"},
    "🕷️Пауки": {"cost": 200, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 18, "emoji": "🕷️"},
    "🦂Сенокосцы": {"cost": 150, "product": "🧪", "min_prod": 1, "max_prod": 3, "price_per_unit": 15, "emoji": "🦂"},
    "🐜Термиты": {"cost": 90, "product": "🧪", "min_prod": 2, "max_prod": 5, "price_per_unit": 9, "emoji": "🐜"}
}

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///farm.db")
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ADMIN_ID = 8261666607
